Adds backup and restore for standalone
quay/quay-docs pull request #500
Opened 2022-09-07 13:41 UTC by stevsmit

2022-09-12 10:19 UTC, dmesser requested changes

2022-09-12 10:19 UTC, dmesser commented on modules/backing-up-red-hat-quay-standalone.adoc
> +
We should probably recommend to delete the `quay-config.yaml` file as it contains sensitive information and the configuration is already backed up in the `quay-backup.tar.gz` file.

2022-09-12 10:19 UTC, dmesser commented on modules/backing-up-red-hat-quay-standalone.adoc
> +
We should probably advise the user to also back up the container run command (and thus the container specification) with something like this:

```bash
$ podman inspect quay-app | jq -r '.[0].Config.CreateCommand | .[]' | paste -s -d ' ' -

/usr/bin/podman run --name quay-app -v /etc/quay-install/quay-config:/quay-registry/conf/stack:Z -v /etc/quay-install/quay-storage:/datastorage:Z registry.redhat.io/quay/quay-rhel8:v3.7.5
```

2022-09-12 10:19 UTC, dmesser commented on modules/restoring-red-hat-quay-standalone.adoc
> +
Use the saved container run command from the backup section read back from a file and change any impacted paths to `/opt/new-quay-install` where applicable.

2022-10-09 05:24 UTC, huweihua-redhat commented on modules/backing-up-red-hat-quay-standalone.adoc
> +$ pg_dump -h 172.24.10.50 -d quay -U <username> -W -O > /tmp/quay-backup/quay-backup.sql
When I tried to dump postgresql database, the command I used is
```
$ pg_dump -h <postgresql_host> -p 5432 -d quay  -U  <username>   -W -O > /tmp/quay-backup/quay-backup.sql
```
I think the port attribute is necessary.

2022-10-09 05:49 UTC, huweihua-redhat commented on modules/backing-up-red-hat-quay-standalone.adoc
> +----
When I run verification test, I was using AWS S3 bucket.  
```
DISTRIBUTED_STORAGE_CONFIG:
  default:
    - S3Storage
    - s3_bucket: whuquay
      storage_path: /registry 
      s3_access_key: A.....P 
      s3_secret_key: c......V4
      host: s3.us-east-2.amazonaws.com

```

The sync  command is 
```
$ aws s3 sync  s3://whuquay   /tmp/quay-backup/blob-backup/  --source-region us-east-2
download: s3://whuquay/registry/sha256/9c/9c3181779a868e09698b567a3c42f3744584ddb1398efe2c4ba569a99b823f7a to registry/sha256/9c/9c3181779a868e09698b567a3c42f3744584ddb1398efe2c4ba569a99b823f7a
download: s3://whuquay/registry/sha256/e9/e9c5463f15f0fd62df3898b36ace8d15386a6813ffb470f332698ecb34af5b0d to registry/sha256/e9/e9c5463f15f0fd62df3898b36ace8d15386a6813ffb470f332698ecb34af5b0d


[hwh@localhost blob-backup]$ tree ./
./
└── registry
    └── sha256
        ├── 9c
        │   └── 9c3181779a868e09698b567a3c42f3744584ddb1398efe2c4ba569a99b823f7a
        └── e9
            └── e9c5463f15f0fd62df3898b36ace8d15386a6813ffb470f332698ecb34af5b0d

```

2022-10-09 06:07 UTC, huweihua-redhat commented on modules/restoring-red-hat-quay-standalone.adoc
> +----
Depending on the guide of step 5 to step 12, I suppose this example is to back up one database to another database in the same postgresql server.  So in my verification test,  I was trying to back up data from database `quay` to new database `example_restore_registry_quay_database ` in the same postgresql server `whupsql1.postgres.database.azure.com`.

*  back up `quay` database
```
$ pg_dump -h whupsql1.postgres.database.azure.com -p 5432 -d quay -U w...y -W -O  > /tmp/quay-backup/quay-backup.sql
```
 
* create new database `example_restore_registry_quay_database`
```
$ psql "host=whupsql1.postgres.database.azure.com port=5432 dbname=postgres user=w..y password=A...2"
postgres=> CREATE DATABASE example_restore_registry_quay_database;
CREATE DATABASE

postgres=> \c example_restore_registry_quay_database;

example_restore_registry_quay_database=> CREATE EXTENSION IF NOT EXISTS pg_trgm;
CREATE EXTENSION

example_restore_registry_quay_database=> \q

$ psql "host=whupsql1.postgres.database.azure.com port=5432 dbname=example_restore_registry_quay_database user=w..y " -W <  /tmp/quay-backup/quay-backup.sql
```

2022-10-09 06:12 UTC, huweihua-redhat commented on modules/restoring-red-hat-quay-standalone.adoc
> +----
If customer try to move database from one postgrepsql server to another postgrepsql server.  Customer have to update `DB_URI ` setting in `config.yaml` before restarting the quay.
```
DB_URI: postgresql://<username>:<password>@<new_postgrepsql_host>:5432/example_restore_registry_quay_database

```

2022-10-09 06:23 UTC, huweihua-redhat commented on modules/restoring-red-hat-quay-standalone.adoc
> +DISTRIBUTED_STORAGE_DEFAULT_LOCATIONS: []
If the example is to back up image data from one S3 storage and restore image data to another S3 storage,  customer need to update `DISTRIBUTED_STORAGE_CONFIG` setting in  `/opt/new-quay-install/config.yaml` before restarting the quay.

2022-10-09 06:24 UTC, huweihua-redhat commented on modules/restoring-red-hat-quay-standalone.adoc
> +----
When I run verification test, I was using AWS S3 bucket. So the command I used to create new bucket is 
```
$aws s3 mb s3://whuquay1  --region us-east-2

```

2022-10-09 06:56 UTC, huweihua-redhat commented on modules/restoring-red-hat-quay-standalone.adoc
> +
There is one thing I need to highlight.   The quay registry endpoint should be the same before backup and after resotre.  

For example,  when I try to move the quay from VM1(whuvm.eastus.cloudapp.azure.com) to VM2(whuvm2.eastus.cloudapp.azure.com).   

Before backup, I push one image `whuvm.eastus.cloudapp.azure.com/org1/repo1:ppc64le`.   Then I found there are many information about `whuvm.eastus.cloudapp.azure.com` in `/tmp/quay-backup/quay-backup.sql`. So after restoring postgresql data,  access quay by  `http://whuvm2.eastus.cloudapp.azure.com/repository/org1/repo1`.   The value of `Pull this container with the following Docker command:` in webpage still is `docker pull whuvm.eastus.cloudapp.azure.com/org1/repo1`.  This message should be come from database.  

Try to pull image from `whuvm2.eastus.cloudapp.azure.com/repository/org1/repo1` will be timeout.

2022-10-26 14:19 UTC, huweihua-redhat commented on modules/restoring-red-hat-quay-standalone.adoc
> +postgres=> CREATE DATABASE example_restore_registry_quay_database;
The value of `host` is the postgresql route used by customer,   it does not always equal `<user_name>.postgres.database.azure.com`.  For example, when I set up postgresql on azure,  the host is `whupsql1.postgres.database.azure.com`, the login user name is `whuquay`. In `config.yaml`, the DB_URI is `postgresql://whuquay:password@whupsql1.postgres.database.azure.com/quay`.  

The  DB_URI  format is `postgresql://<login_user_name>:<login_user_password>@<postgresql_host>/<quay_database>`.

So in customer's environment, line77 should be `psql "host=<<postgresql_host>  port=5432 dbname=<quay_database> user=<login_user_name>  password=<login_user_password>"`

2022-10-26 14:35 UTC, huweihua-redhat commented on modules/restoring-red-hat-quay-standalone.adoc
> +. Set the password for your PostgreSQL deployment by running the following command:
What we do here is to import  database backup to the new database, not to set the password.

2022-10-26 14:38 UTC, huweihua-redhat commented on modules/restoring-red-hat-quay-standalone.adoc
> +$ psql "host=<user_name>.postgres.database.azure.com port=5432 dbname=example_restore_registry_quay_database user=w..y " -W <  /tmp/quay-backup/quay-backup.sql
It is better to go as 
```
$ psql "host=<<postgresql_host> port=5432 dbname=example_restore_registry_quay_database user=<login_user_name> password=<login_user_password>" -W <  /tmp/quay-backup/quay-backup.sql
```

2022-10-26 15:18 UTC, huweihua-redhat commented on modules/backing-up-red-hat-quay-standalone.adoc
> +----
we can remove ` <---------this line` here. 

`<user_name>` should be `<bucket_name>`.

2022-10-26 15:19 UTC, huweihua-redhat commented on modules/backing-up-red-hat-quay-standalone.adoc
> +$ aws s3 sync s3://<user_name> /tmp/quay-backup/blob-backup/ --source-region us-east-2
should be 
```
$ aws s3 sync s3://<bucket_name>  /tmp/quay-backup/blob-backup/ --source-region us-east-2
```

2022-10-26 15:20 UTC, huweihua-redhat commented on modules/restoring-red-hat-quay-standalone.adoc
> +----
should be 
```
DISTRIBUTED_STORAGE_CONFIG:
   default:
DISTRIBUTED_STORAGE_CONFIG:
   default:
    - S3Storage
    - s3_bucket: <bucket_name>
      storage_path: /registry 
      s3_access_key: <s3_access_key>
      s3_secret_key: <s3_secret_key>
      host: <host_name>
```

2022-10-26 15:21 UTC, huweihua-redhat commented on modules/restoring-red-hat-quay-standalone.adoc
> +make_bucket: <user_name>
should be 
```
$ aws s3 mb s3://<new_bucket_name>  --region us-east-2
make_bucket: <new_bucket_name> 
```

2022-10-27 07:38 UTC, huweihua-redhat commented on modules/restoring-red-hat-quay-standalone.adoc
> +
Here,  it is better to remind customer to update storage setting in the `config.yaml` before restarting the quay like line 139. 
```
DISTRIBUTED_STORAGE_CONFIG:
   default:
DISTRIBUTED_STORAGE_CONFIG:
   default:
    - S3Storage
    - s3_bucket: <new_bucket_name>       
      storage_path: /registry 
      s3_access_key: <s3_access_key>
      s3_secret_key: <s3_secret_key>
      host: <host_name>
```

2022-10-28 07:15 UTC, huweihua-redhat commented
LGTM
Thanks so much

2022-10-31 13:23 UTC, merged