34 release notes
quay/quay-docs pull request #95
Opened 2020-10-14 17:09 UTC by BillDett

First draft- needs known issues added following QE testing.

2021-01-04 15:52 UTC, thomasmckay requested changes

2021-01-04 15:52 UTC, thomasmckay commented on modules/rn_3_40.adoc
> +* Quay Builders are now supported only on OpenShift/Kubernetes and utilize Fedora CoreOS for builder sandbox VMs.  Quay Build Manager completely re-written to use gRPC and address numerous issues.
s/Fedora CoreOS/Red Hat CoreOS (RHCOS)/

2021-01-04 15:52 UTC, thomasmckay commented on modules/rn_3_40.adoc
> +FEATURE_HELM_OCI_SUPPORT = True
```
FEATURE_GENERAL_OCI_SUPPORT: true
FEATURE_HELM_OCI_SUPPORT: true
```

2021-01-04 15:52 UTC, thomasmckay commented on modules/rn_3_40.adoc
> +* PROJQUAY-1132 running as config should not try to set httppasswd
Whitespace cleanup (or replace tabs with whitespace?)

2021-01-04 15:52 UTC, thomasmckay commented on modules/rn_3_40.adoc
> +* Only supported on OCP-4.2 or newer
OCP N-2 is 4.5

2021-01-04 15:52 UTC, thomasmckay commented on modules/rn_3_40.adoc
> +* Only supported on OCP-4.2 or newer
OCP N-2 is 4.5

2021-01-04 16:27 UTC, BillDett commented on modules/rn_3_40.adoc
> +* New ConfigTool replaces the older Config App, providing better configuration validation and integration with the new Quay Operator.  Quay now uses same validator as the Config Tool at start time to
no- just pointing out that Quay now uses the same config validation at startup time as our ConfigTool (Jonathan's nifty table).  Perhaps I haven't made that clear enough- I can add some more words.

2021-01-04 16:27 UTC, BillDett commented on modules/rn_3_40.adoc
> +* Quay Builders are now supported only on OpenShift/Kubernetes and utilize Fedora CoreOS for builder sandbox VMs.  Quay Build Manager completely re-written to use gRPC and address numerous issues.
good catch

2021-01-04 16:27 UTC, BillDett commented on modules/rn_3_40.adoc
> +FEATURE_HELM_OCI_SUPPORT = True
ACK

2021-01-04 16:27 UTC, BillDett commented on modules/rn_3_40.adoc
> +* PROJQUAY-1132 running as config should not try to set httppasswd
ACK

2021-01-04 16:27 UTC, BillDett commented on modules/rn_3_40.adoc
> +* Only supported on OCP-4.2 or newer
ACK

2021-01-04 16:27 UTC, BillDett commented on modules/rn_3_40.adoc
> +* Only supported on OCP-4.2 or newer
ACK

2021-01-06 19:41 UTC, closed without merging

2021-01-06 19:53 UTC, BillDett commented
Closing this PR as it's gone pretty stale- raised final changes via https://github.com/quay/quay-docs/pull/113